### ISSUE TITLE
你好,blcoud启动不了,出现错误.

### ISSUE THREAD

**Issue by wang8o** [LiuLang/bcloud-packages#124]
感谢您写了bcloud这个程序,方便了很多linux用户.
偶现在用的是linuxmint 17.1, 用的是kde,昨天还能启动bcloud下载文件,今天就启动不了.
终端下运行bcloud-gui出现以下错误.
 (bcloud-gui:11267): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(bcloud-gui:11267): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
跟踪/断点陷阱
这个错误和https://github.com/LiuLang/bcloud-packages/issues/107 这里的错误很像,但偶是小白,完全没办法解决.
谢谢咯^_^

**Comment by wang8o** [comment]
补充一下,偶是用 sudo dpkg -i bcloud.deb安装的

**Comment by LiuLang** [comment]
请看一下~/.config/bcloud/bcloud-stderr.log 这个日志文件, 里面都有什么内容.
而且bcloud跟gtk2完全扯不上关系, 出现这样的问题很是奇怪.

**Comment by wang8o** [comment]
偶在/home/wang8o/.config/bcloud/找到bcloud-stderr.log这个文件,全文如下
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 279, in download
    os.remove(tmp_filepath)
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/wang8o/下载/temp/150121 쇼챔피언/150121 쇼챔피언 [종현] - 데자부.tp.part'

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 279, in download
    os.remove(tmp_filepath)
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/wang8o/下载/temp/150121 쇼챔피언/150121 쇼챔피언 [하이포] - 비슷해.tp.part'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b/temp'

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b/temp'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 296, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 147, in download
    os.makedirs(row[SAVEDIR_COL], exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] 权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b'

**Comment by LiuLang** [comment]
权限不够: '/media/wang8o/e92ce1c1-12f7-4679-ab2b-b6cb3ba6fa3b
这个是什么目录? 当前用户有写入权限么?

**Comment by wang8o** [comment]
好久没来了，问题解决了，删掉/home/wang8o/.config/bcloud/ 下面的所有文件又能用了，谢谢喽
