### ISSUE TITLE
刚更新了软件，但打不开

### ISSUE THREAD

**Issue by behind1231** [LiuLang/bcloud-packages#133]
如题，在终端运行显示如下代码：behind@localhost:~$ bcloud-gui
Traceback (most recent call last):
  File "/usr/sbin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.4/site-packages/bcloud/App.py", line 37, in <module>
    from bcloud.FileWatcher import WatchFileChange
  File "/usr/lib/python3.4/site-packages/bcloud/FileWatcher.py", line 8, in <module>
    import pyinotify
ImportError: No module named 'pyinotify'
behind@localhost:~$

**Comment by behind1231** [comment]
作者这是什么问题，有些急用，谢谢

**Comment by LiuLang** [comment]
On 05/16/2015 03:52 PM, YGOCore-monocompile wrote:
> 作者这是什么问题，有些急用，谢谢
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud-packages/issues/133#issuecomment-102585259
>

哦, 新版本里需要pyinotify这个包. 我刚才重新制作了deb包, 你可以重新安装试试.

**Comment by behind1231** [comment]
我是ARCHLINUX系统

**Comment by LiuLang** [comment]
On 05/16/2015 04:03 PM, YGOCore-monocompile wrote:
> 我是ARCHLINUX系统
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud-packages/issues/133#issuecomment-102585561
>
那你可以先手动安装好python3-pyinotify. 可能包的名称不一样, 你找找看, 是 
inotify的python3绑定
