### ISSUE TITLE
bcloud_3.7.2-1_all.deb 下载错误

### ISSUE THREAD

**Issue by widon1104** [LiuLang/bcloud-packages#149]
有时候下载会发生错误，可否在发生错误时候自动隔一段时候候重试，而不是提示错误后再也不尝试，必须手动开启下载

**Comment by jtliaw** [comment]
3.7.1.-3_all.deb的包比较不会有错误！建议使用3.7.1.-3_all.deb！
https://mega.nz/#!2tQ2CRaC!kaPGW3BZuW60daK4Vks0z05uoxhNzaFAYaf6Oqv74G8

**Comment by widon1104** [comment]
使用3.7.1.-3_all.deb下载时依旧会提示状态错误，必须点击开始下载按钮继续下载

**Comment by jtliaw** [comment]
大神更新了bcloud！你再试试看最新版本！

**Comment by widon1104** [comment]
bcloud_3.8.1-1_all.deb还是不好使，我下载一个视频，马上就提示错误，然后不再自动恢复下载了，直接用firefox下载没问题，就是速度有点慢

**Comment by jtliaw** [comment]
试试看！将bcloud---首选项---下载---每个下载任务改为1个链接看看！

**Comment by widon1104** [comment]
3.8.1-1，同时上传设置为1，也会报错误

**Comment by widon1104** [comment]
上传发生错误以后，我把所有任务暂停，然后开始，系统僵死过2次，必须重启电脑才能恢复。
错误状态，在多个版本，下载和上传时都可能发生，而且比较容易出现。
我是用的系统是ubuntu-mate 15.04 mate。

**Comment by jtliaw** [comment]
这要等liulang大神来回答了，我的Lubuntu14.04,未曾见过你的情况！

**Comment by widon1104** [comment]
我的几个较大文件(1.x G)，在早上上传成功了，，晚上死活没速度。
上传的时候能否显示上传速度啊，不然的化容易出问题，有一次我早上开了很多上传任务，结果晚上回家，除了几个很小的srt文件，其余的大视频文件一个都没上传成功。

**Comment by cassial** [comment]
百度典型是个作恶的公司

**Comment by jtliaw** [comment]
这一点确实如此！在bcloud上传绝对比下载糟糕！不过我相信这应该是百度网页版的问题，因为要大家使用他的客户端！

**Comment by LiuLang** [comment]
@widon1104 请把你的日志文件贴出来或者发到我邮箱吧, 位于 ~/.config/bcloud/目录, 有两个文件.

**Comment by alienhjy** [comment]
@LiuLang 我认为 widon1104 要说的问题跟我是同一个问题。。。就是很多资源下载的时候会出现错误。我看bcloud.log里面的问题基本都是同一个，就贴其中一小段吧。bcloud-stderr.log是空的。。。

```
2015-12-12 22:49:23,710 ERROR Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/bcloud/Downloader.py", line 77, in get_req
    return opener.open(self.url, timeout=self.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 503, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 503, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by zw963** [comment]
我的也是楼上那个错误，LinuxMint 17.3, 3.8.2 的 bcloud 客户端。

>> HTTP Error 403: Forbidden
